# -*- coding: utf-8 -*-
{
'name': "ZKteco Integration",
    'summary': """Integration with ZKTeco Biometric Devices""",
    'description': "",
    'license': 'OPL-1',
    'author': "Osynx Solutions",
    'website': "https://www.osynx.odoo.com",
    'category': 'Human Resources',
    'version': '0.1',
    'depends': ['base', 'hr', 'hr_contract', 'hr_attendance', 'resource','portal','rating'],
    'data': [
        'data/zk_techo_data.xml',
        'data/mail_channel.xml',
        'security/biometricdevice_security.xml',
        'security/ir.model.access.csv',
        'wizard/upload_employee_views.xml',
        'wizard/transfer_data_views.xml',
        'views/res_config_settings_view.xml',
        'views/hr_attendance_view.xml',
        'views/hr_employee_views.xml',
        'views/biometric_device_view.xml',
        'views/biometric_logs_views.xml',
        'views/biometric_user_views.xml',
        # 'views/hr_extensionview.xml',
        'wizard/upload_employee_views.xml',
        'views/menuitem.xml',

    ],
    'images':  ["static/description/image.png"],
    'price' : 500,
    'currency' :  'USD',
    'installable': True,
    'auto_install': False,
    'application':False,
    'external_dependencies': {
        'python' : ['pyzk'],
    },
}
